[[file:LICENSE.txt][https://img.shields.io/badge/License-MIT-blue.svg]]
* Syndicate
This is a package for evil organization; it establishes evil-mode bindings for org-mode.
As it is, this borrows heavily from [[https://github.com/edwtjo][edwtjo's]] [[https://github.com/edwtjo/evil-org-mode][evil-org-mode]].
Having used it, I had a love-hate relationship with it.
The keybindings were convenient, however, there were issues:
- leader commands would override my own
- hitting =O= on a heading would insert another heading above it
The leader part was what got me to make a separate package, because I imagine that some users will want some predefined maps of that sort, but having conflicting bindings and looking to migrate to [[https://github.com/noctuid/general.el][general.el]], I decided that pull requests would not cut it.
* Key Bindings
| Key   | Command                         |
|-------+---------------------------------|
| gh    | outline-up-heading              |
| gj    | org-forward-heading-same-level  |
| gk    | org-backward-heading-same-level |
| gl    | outline-next-visible-heading    |
| <     | org-metaleft                    |
| >     | org-metaright                   |
| t     | org-todo                        |
| <tab> | org-cycle                       |
* Commands
- =syndicate-open-links= :: Open a link from a visual selection
- =syndicate-open-links-incognito= :: Open a link in incognito from a visual selection
- =syndicate-recompute-clocks= :: recompute clocks from a visual selection
* Tips
- In terminal mode, =<tab>= for =org-cycle= does not work (at least for me). To fix this, put this before =(require 'evil)=:
  #+begin_src emacs-lisp
    (setq evil-want-C-i-jump nil)
  #+end_src
- I use [[https://github.com/noctuid/general.el][general.el]] for extra bindings.
  Personally, I use this for some org-mode bindings:
  #+begin_src emacs-lisp
    (general-define-key "oa" 'org-agenda ;; o<rg>a<genda>
                        "oc" 'org-capture) ;; o<rg>c<apture>
  #+end_src
  with these as some defaults:
  #+begin_src emacs-lisp
    (setq general-default-prefix "SPC")
    (setq general-default-states '(normal motion visual))
  #+end_src
  - =<leader>= bindings are great for declaring a wealth of global keybindings.
    Because of the diversity in people's =<leader>= bindings, I made the above behavior the choice of the user.
